# Generated by Django 2.0 on 2018-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
