# Generated by Django 2.0 on 2018-11-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_project_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='title',
        ),
    ]
