# Generated by Django 2.0 on 2018-11-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_auto_20181116_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desctiption',
            new_name='descrtiption',
        ),
    ]
