# Generated by Django 2.0 on 2018-11-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_auto_20181116_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
