# Generated by Django 2.0 on 2018-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0007_auto_20181117_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='screenshots/'),
        ),
    ]
